#!/usr/bin/env bash

# Function to install Nginx and configure custom HTTP response header
function configure_nginx() {
    sudo apt-get update -y -qq
    sudo apt-get install -y nginx -qq

    # Ignore shellcheck warning SC2154 for this function
    # shellcheck disable=SC2154
    if [ "$?" -ne 0 ]; then
        echo "Error: Failed to install Nginx."
        exit 1
    fi

    # Configure custom HTTP response header
    sudo sed -i '/server_tokens/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

    # Restart Nginx service to apply changes
    sudo systemctl restart nginx
}

# Main function
main() {
    configure_nginx
}

# Execute main function
main

